"Traceback (most recent call last):\n  File \"/Users/gaz/.ansible/tmp/ansible-tmp-1638662266.836564-3562-164110424164094/AnsiballZ_ping.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/gaz/.ansible/tmp/ansible-tmp-1638662266.836564-3562-164110424164094/AnsiballZ_ping.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/gaz/.ansible/tmp/ansible-tmp-1638662266.836564-3562-164110424164094/AnsiballZ_ping.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.ping', init_globals=dict(_module_fqn='ansible.modules.ping', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/f3/g2rf75dn7vldc44t2wbqtk500000gn/T/ansible_ansible.builtin.ping_payload_47dkkxgv/ansible_ansible.builtin.ping_payload.zip/ansible/modules/ping.py\", line 90, in <module>\n  File \"/var/folders/f3/g2rf75dn7vldc44t2wbqtk500000gn/T/ansible_ansible.builtin.ping_payload_47dkkxgv/ansible_ansible.builtin.ping_payload.zip/ansible/modules/ping.py\", line 80, in main\nException: boom\n",
